### ISSUE TITLE
Variable stellar positions

### ISSUE THREAD

**Issue by gbernstein** [rmjarvis/Piff#10]
In some use cases we will want to enforce a centering criterion on the PSF model (e.g. that its centroid is zero) and leave the positions of the stars as free parameters.  We can begin with the other case (stellar positions are fixed a priori and PSF model is allowed to have non-zero centroid), but this issue is to collect work that would need to be done to implement the former case.  Some aspects of this:
- stardata class will need to support redefinition of the (x,y) of the star.
- Models will need to provide some derivatives of the PSF with respect to (x,y), or perhaps just a routine to re-optimize (x,y) with the current values of PSF parameters
- Models will need to define and implement the centering constraints on the PSF model and enforce it while fitting for PSF parameters.

**Comment by rmjarvis** [comment]
I think the Model base class should take a parameter about whether to recenter or not.  For the one model class we have yet, I don't think there is currently any hook in the hsm routine to keep it from recenter.  So that will require an update to the routine in GalSim.  For now maybe just issue a warning that it can't respect the fix_center=True directive.

Then the LinearModel class (the base class for the PixelModel and other linear models) should work with the derivative matrices as we talked about during the hack session.  We can require that the derived classes from this have routines that return dmodel/duc and dmodel/dvc matrices.  It can then handle the outer loop process to iterate on the center position.

Also, one minor nomenclature point.  I think we should avoid the use of "centroid" if possible.  I've been trying to remember to say "nominal center" in the documentation so far about this (although there may be places where I slipped and wrote centroid).  I think we should allow models to treat the "center" in whatever way they want.  It doesn't have to represent any particular definition of a centroid (weighted or otherwise).  Just something that has a consistent definition across all the stars being modeled.

**Comment by gbernstein** [comment]
Right, instead of a "centroid" I would refer to a "centering condition" on the PSF model (which could of course be that the centroid is zero, or some windowed centroid, or whatever...).  So we would leave it up to the Model, when doing its fitting for parameters, to enforce this condition, and marginalize over the center uc,vc of the star.  Still would be good though to put the new uc,vc back into the stardata.

One ugly thing is going to be that enforcing a flux or centering condition on the Model is going to reduce the number of degrees of freedom.  For a pixelized model, we could just remove 1 (2) of the pixels as free parameters if we enforce a flux (centering) condition, since they are now determined by the other pixels' values. This would have the virtue that the interpolator could not create un-centered PSFs.

**Comment by rmjarvis** [comment]
The name for this in the PixelGrid class is `force_model_center`.  When True, the PSF model is fixed to have center at (0,0), and the corresponding location on the input image is allowed to float.  When False, the positions of the stars is trusted to be accurate and fixed at the input values.  The resulting model might thus have an off-center centroid.
