### ISSUE TITLE
Caching atmospheric params to be more efficienct about making diagnostic plots

### ISSUE THREAD

**Issue by eacharles** [rmjarvis/Piff#100]
In running the diagnostic plots Ares found that code was very slow because it was repeatedly getting the atmospheric parameters for the stars.  

If you look in the eac-dev branch in some of the stats objects you will see that he added flag to signal the optatmo_psf that it did not need to recompute those parameters.   The particular files affected are:

+++ b/piff/star_stats.py
+++ b/piff/stats.py
+++ b/piff/twod_stats.py

And there is code like:
-        self.models = psf.drawStarList(self.stars)
+        if trust_atmo_params_stored_in_stars ==True:
+            self.models = psf.drawStarList(self.stars, trust_atmo_params_stored_in_stars=True)
+        else:
+            self.models = psf.drawStarList(self.stars)

I suspect that Mike has an alternate way of doing this.   
It would be good to agree on how to handle this.   It really speeds up the diagnostic plot making.

**Comment by rmjarvis** [comment]
I don't understand the reason for this.  If the values are already computed, why not just use them.  In other words, what is the use case for `trust_atmo_params_stored_in_stars=False`?

**Comment by eacharles** [comment]
Well, Ares, will need to comment more.   But I think that the root problem is that the star.fit is being overloaded to refer to two versions of the atmospheric fit parameters, (orginal and interpolated) and so when the getParamsList is called, it need to know if it should be using the original version or getting the interpolated version:  the relevant code looks like this:
`                if trust_atmo_params_stored_in_stars:
                    aberrations_atmo_star = np.array([star.fit.params for star in stars])[:,0:3]
                else:
                    # strip star fit
                    stars = [Star(star.data, None) for star in stars]
                    stars = self.atmo_interp.interpolateList(stars)
                    aberrations_atmo_star = np.array([star.fit.params for star in stars])
                params[:, 0:3] += aberrations_atmo_star
`

**Comment by rmjarvis** [comment]
I think the appropriate thing here is to have `drawStarList` check if `star.fit.params is not None` for all the stars being drawn, in which case, don't redo the interpolation.

Doing this for SimplePSF passes all tests, so I think this doesn't break any assumptions we are currently making.  Probably redoing the interpolation was just to make sure things are set.  If they are already set, it's redundant.  Likely whoever originally wrote this (either me or Chris I suspect) didn't anticipate this as an efficiency concern, so we didn't try to optimize it.

Specifically, this diff passes all tests on master:
```
diff --git a/piff/simplepsf.py b/piff/simplepsf.py
index b6cb659..91ed03e 100644
--- a/piff/simplepsf.py
+++ b/piff/simplepsf.py
@@ -239,9 +239,10 @@ class SimplePSF(PSF):
         :returns:           List of Star instances with its image filled with
                             rendered PSF
         """
-        stars_interpolated = self.interp.interpolateList(stars)
-        stars_drawn = [self.model.draw(star, copy_image=copy_image) for star in stars_interpolated]
-        return stars_drawn
+        if any(star.fit is None or star.fit.params is None for star in stars):
+            stars = self.interp.interpolateList(stars)
+        stars = [self.model.draw(star, copy_image=copy_image) for star in stars]
+        return stars
 
     def drawStar(self, star, copy_image=True):
         """Generate PSF image for a given star.
@@ -255,8 +256,9 @@ class SimplePSF(PSF):
         :returns:           Star instance with its image filled with rendered PSF
         """
         # Interpolate parameters to this position/properties:
-        star = self.interp.interpolate(star)
-        self.model.normalize(star)
+        if star.fit is None or star.fit.params is None:
+            star = self.interp.interpolate(star)
+            self.model.normalize(star)
         # Render the image
         return self.model.draw(star, copy_image=copy_image)
```

**Comment by areshernandez** [comment]
A lot of this may soon no longer be an issue. In some of my most recent changes to the PIFF fitting pipeline I've replaced some of the plots with some of my own that don't require a additional new usage of getParamsList() and deleted some others that I felt were redundant. At this point, (I think), these extra arguments I added may not be necessary anymore. I haven't tested removing them in my fits; however.

In so far as trust_atmo_params_stored_in_stars=False, that was actually the default case before I added this argument (if I remove this this is what it will always be). The reason is that star.fit.params will not be None even in some cases where you want to compute the interpolation to get the interpolated params. Specifically, in the PIFF fitting pipeline the stars that were used in the individual star fit have the values they found in said fit stored inside star.fit.params, and there's no way to know how the stars got these params. In case you have a psf with an atmospheric interpolation and you really want to make sure when you use psf.getParamsList() you get the interpolated atmospheric params you want, you need trust_atmo_params_stored_in_stars=False. Otherwise, you may mistakenly grab the atmo params from the individual star fit instead. trust_atmo_params_stored_in_stars=True was actually the new option I added, so that when you're very sure the stars you have on hand have the fit params appropriate for the psf you are currently using, you don't need to re-interpolate.

**Comment by areshernandez** [comment]
Also, originally, generically-speaking, star.fit.params never had the atmo params from an interpolation in my fits. This is why I made the return_stars_with_atmo_params_from_psf=True, so that star.fit.params could be overwritten with the interpolated values, so you could grab them later without re-interpolating.

**Comment by rmjarvis** [comment]
I didn't follow all that.  But it sounds like you should have separate functions called `getParamList` and `computeParamList`.  Then when you really want to recompute it, call the second one.  And when you just want to grab it (and compute if necessary), call the first one.

**Comment by areshernandez** [comment]
In principle I agree, but every instance of getParamsList() in optatmo-based PIFF and the PIFF fitting pipeline right now is set up to expect something with the functionality of "computeParamList()," so I'd have to carefully change a lot. Ultimately, getParamsList() should have never been given the name "get" since that's not what that function is actually doing but fixing that at this stage would be difficult. 

I think what we're likely to end up doing is swallowing that getParamsList() doesn't actually get stuff (for the atmo params). As I said, I haven't tested this, but with recent changes I made to the PIFF fitting pipeline there are no longer any instances that need something that grabs the atmo params, so changing things back to the way they were may work.

**Comment by rmjarvis** [comment]
OK, it sounds like this requires some adjustments in how some of the OptAtmo stuff works, but I don't see there being anything here that needs to be brought onto master.  Closing.

**Comment by eacharles** [comment]
Sorry, I'm a bit confused.   What about the extra check on star.fit is None you suggested above before redoing the interpolation.   Isn't that something that we would want in general?

**Comment by rmjarvis** [comment]
Sure.  I think that change would be fine to get onto master.  I don't think it is specifically relevant for the optatmo branch, but there might be use cases where this is a modest efficiency gain.

**Comment by eacharles** [comment]
Ok.  I guess you will handle yourself, since you already have code you've tested.
