### ISSUE TITLE
Add additional models in optical_model.py

### ISSUE THREAD

**Issue by eacharles** [rmjarvis/Piff#102]
In the galsimify branch of the code Ares has added a couple of optical models.  You can see those changes on the eac-dev branch.   

In particular there are a couple of new templates.

````
+    'des': {
+        'obscuration': 0.301 / 0.7174,
+        'nstruts': 4,
+        'diam': 4.274419,  # meters
+        'lam': 700, # nm
+        # aaron plays between 19 mm thick and 50 mm thick
+        'strut_thick': 0.050 * (1462.526 / 4010.) / 2.0, # conversion factor is nebulous?!
+        'strut_angle': 45 * galsim.degrees,
+        'r0': 0.1,
+    },
+    'des_big_r0': {  # Same as des, but r0 = 0.15
+        'obscuration': 0.301 / 0.7174,
+        'nstruts': 4,
+        'diam': 4.274419,
+        'lam': 700,
+        'strut_thick': 0.050 * (1462.526 / 4010.) / 2.0,
+        'strut_angle': 45 * galsim.degrees,
+        'r0': 0.15,
+    },
+    'des_vonkarman': {  # Same as des, but with L0.
+        'obscuration': 0.301 / 0.7174,
+        'nstruts': 4,
+        'diam': 4.274419,
+        'lam': 700,
+        'strut_thick': 0.050 * (1462.526 / 4010.) / 2.0,
+        'strut_angle': 45 * galsim.degrees,
+        'r0': 0.15,
+        'L0': 25.0,
+    },
`
```

Also, I think that we probably want to sub-class the Optical class.   There are a number of different cases being handled in the new code that would probably be better handled with polymorphism.

**Comment by rmjarvis** [comment]
These seem like they should be user inputs, not extra templates.  The template structure is just a convenience, and you can override values with additional kwargs.  So e.g. `des_big_r0` should really be
```
Optical(template='des', r0=0.15)
```
and `des_vonkarman` is
```
Optical(template='des', r0=0.15, L0=25)
```

**Comment by eacharles** [comment]
Hmm...   What about the fact that the VonKarman has an additional parameter.   Ares's code has a number of messy iff statements dealing with that.   Wouldn't it be better to sub-type?

**Comment by rmjarvis** [comment]
Well, the current code doesn't support L0 at all.  But Kolmogorov is equivalent to L0=inf.  So we could easily have the default be L0=None.  And then if it's not None, then use VonKarman with that specified L0.  Seems like that could be made pretty clean to me.

**Comment by areshernandez** [comment]
I've been reviewing this change and trying to remember why I did it and I think I have a vague idea of what happened (the short answer is this was the easiest way for me to deal with some problems I had at the time):

For des_vonkarman, at the time I was having trouble figuring out a way to get the code to run with one or the other atmosphere easily (I was playing around with both originally before settling on vonkarman). Initially, I just changed the existing des template to have L0 but this caused crashes whenever I tried to do a Kolmogorov atmosphere. In order to make sure I could make it so I would sometimes have L0 and sometimes not, I created the second template to easily be able to do one fit or the other just by specifying the template in the psf_optatmo.yaml file. At one point (I think) I tried using a series of if statements in optical_model.py instead, but I ended up getting confused, so I changed that.

In so far as the big_r0 template is conserved that's because of a time I was last trying to get the unit tests running. The problem was, some optatmo tests were set up to work with r0=0.15 and some optical_model tests were set up to work with r0=0.1 (I remember only finding this out after time travelling with git all the way back until I found a commit where the initial value of r0 was changed). The quickest way I could think of to deal with this problem quickly at the time and move on to fixing other unit tests was just to make another template, since it required only a small amount of change in the unit test code.

**Comment by rmjarvis** [comment]
> this was the easiest way for me to deal with some problems I had at the time

This is not a good reason to add these.  Closing.

**Comment by eacharles** [comment]
Sorry, I'm trying to come up with a set of changes that achieves what we need in the optatmo branch.   

It sounds your are asking that 1) we use `None` as a guard value to distinguish between VonKarman and Komolgorov  (I'm not sure that sub-typing wouldn't be better, but hey, it's your package)   2). Ares' is asking from some mechanism to easily pass parameter sets from the configuration file to the Optical object.   He was using the templates to do that, and you are suggesting that instead it should be done some other way.  What exactly do you have in mind?  Was just to include the entire parameter set either in configuration file, and / or to override each of the parameters by hand in the specific test?

**Comment by rmjarvis** [comment]
There is no need to put everything into the template.  The following kwargs are all equivalent:
```
kwargs1 = {'template': 'des_big_r0'}
kwargs2 = {'template': 'des', 'r0': 0.15}
kwargs3 = {'obscuration': 0.301 / 0.7174,
           'nstruts': 4,
           'diam': 4.274419,
           'lam': 700,
           'strut_thick': 0.050 * (1462.526 / 4010.) / 2.0,
           'strut_angle': 45 * galsim.degrees,
           'r0': 0.15}
```
The template thing is just a convenience.  My point is that the second option is not significantly more to write than the first one, so I don't see a compelling case for adding more templates just to avoid one or two explicit overrides.

**Comment by eacharles** [comment]
Ok, got it.  I'll ahve a look at how it is being used in optatmo branch, thanks.

**Comment by eacharles** [comment]
Ok, on the eac-dev branch I came up with changes that do things the way mike is suggesting. 
I'll work on getting those into the galsimify-branch.
