### ISSUE TITLE
Examples in documentation & `examples/` fail for v1.2

### ISSUE THREAD

**Issue by sweverett** [rmjarvis/Piff#130]
Hello - @mcclearyj  and I are interested in replacing PSFEx in a measurement we are working on with Piff due to the same issues found in the DES SV/Y1 analysis (size bias, etc.). However, we pretty quickly ran into issues trying it out for ourselves when looking at the [documentation](http://rmjarvis.github.io/Piff/_build/html/index.html) (though it seems to be for v1.0) and the `examples/` dir. Some of these are pretty minor and can be figured out with some guesswork, but I don't know if there are other important changes that are missing.

1. In the [example](http://rmjarvis.github.io/Piff/_build/html/piffify.html#the-piffify-executable) for the `piffify` executable, it uses the config keywords `input/images` and `input/cats`, which I believe are now `input/image_file_name` and `input/cat_file_name` respectively.

2. Running `piffify examples/desy3.yaml` fails even with `pixmappy` installed, giving the following error:

```
galsim.errors.GalSimConfigError: One of the attributes dict_keys(['yaml_file', 'use_DESMaps']) is required for type = Pixmappy
```
I don't have much experience with `pixmappy`, but there is no example yaml file to use and setting `use_DESMaps=True` will fail both because the file `y6a1.guts.astro` is not present and because the WCS `galsim` config parser is upset that `file_name` is present (don't understand this one, as it is required if the `use_DESMaps` is not present).

3. Removing the `wcs` field from above will allow `piffify examples/desy3.yaml` to successfully run using the WCS in the fits image, but the output includes the following warning:
```
WARNING: Items ['max_snr', 'min_snr', 'reserve_frac', 'seed'] should now be in the 'select' field of the config file.
```
I see that the correct number of stars were held in reserve so I assume that these values are still correctly parsed (and I can understand not wanting to change the DES Y3 example as was run). However, I wasn't able to find any mention of the `select` field anywhere in the docs or what the other options are.

4. After dealing with the above, we got an output Piff file and wanted to draw the PSF but it failed. We eventually realized this was due to not supplying `chipnum=12`, which we didn't think was needed as the example config has the field `psf/type: SingleChip` and the [`PSF.draw()` doc ](http://rmjarvis.github.io/Piff/_build/html/psf.html#piff.PSF) states that:
```
chipnum – Which chip to use for WCS information. [default: 0, which is appropriate if only using a single chip]
```

Sorry for the long bug dump, but hopefully it might be helpful to any other Piff newbies until things are updated :)

**Comment by rmjarvis** [comment]
Thanks Spencer.  And sorry for the troubles.

I've made the following fixes:

1. Set our docs page to use the 1.2 branch, rather than 1.0, so the docs are at least up-to-date with the latest release (even if they are still pretty bare-bones as yet).
2. Added a reminder on my release checklist to do this in the future when we make a new minor version release.
3. Added a comment in desy3.yaml about SingleChip requiring chipnum, even if only 1 chip was given as input.
4. Added a select field in desy3.yaml and moved the items that now belong there into that section.
5. Fixed the wcs section to use yaml_file rather than file_name, which is now (with pixmappy v1.0) the name of that item in the pixmappy code.
6. Expanded some of the annotations in desy3.yaml to hopefully improve its pedagogical value as a getting started guide.

I think this covers all the cruft you uncovered so far, but please do reach out if you find anything else that doesn't work or is incorrectly documented.  (I know the docs are still pretty poor right now, but to the best of my knowledge, what is there should at least be correct.)

**Comment by rmjarvis** [comment]
And,
7. Fix config in [piffify doc page](http://rmjarvis.github.io/Piff/_build/html/piffify.html)

**Comment by mcclearyj** [comment]
Thank you, Mike. This is very helpful indeed!
