### ISSUE TITLE
PSFEnt

### ISSUE THREAD

**Issue by rmjarvis** [rmjarvis/Piff#17]
Let's include PSFEnt as an option.

cf. http://arxiv.org/abs/1206.1383

**Comment by rmjarvis** [comment]
Some comments about this from @chihway:

>  As you probably already know, the code is hosted [here](https://bitbucket.org/drphilmarshall/psfent/wiki/Home).

> I’m happy to explain the basic implementation and tests we’ve done. What I’m not completely sure is whether it’s easily extended (or computationally practical) to interpolate something more complicated than just e1/e2 as we did in that paper. Also related to what I brought up in the meeting, I think we would benefit from some DES data that could properly sample the atmospheric PSF so we can cross-check the sims, something like what Aaron used for the donut studies.  

> I also have to admit that @drphilmarshall did most of the coding (it was an extension to his LensEnt code). I was mainly involved in designing the sims and doing the analysis.

**Comment by drphilmarshall** [comment]
Great that you are interested in using PSFEnt, but you should be aware that
it is not open source code (for reasons beyond my control, sorry!). The
MemSys5 kernel it uses has an academic use license that must be signed
(with a signature, not a mouse click) and sent (either by fax(!) or
electronic PDF) to MaxEndt Data Consultants by each person who uses the
code. I can enquire (again) if they are willing to re-license the code with
modified BSD, but until then you can get the license from
https://drphilmarshall.github.io/PSFEnt/

NB. Chihway, I made a mirror of the private Bitbucket repo on GitHub in
order to expose the license file. I'll add you as a collaborator. the
webpage is in the gh-pages branch, along with just the license file and a
copy of your paper.

**Comment by rmjarvis** [comment]
Agreed.  We'll make sure not to use any of the MemSys5 code so as not to run afoul of their license.  Hopefully Yuki can write equivalent functionality based on the math in your paper.

**Comment by drphilmarshall** [comment]
If you have the development time, I agree with Erin - the MaxEnt license is
a pain. The main things to take from the PSFEnt project are: 1) there are
gains to be made beyond simple linear polynomial interpolations and 2) you
can learn a lot about hyper-parameters of PSF field models (or more
accurately, the priors on thosehyper-parameters) from realistic physical
simulations.

If I was to re-do the PSFEnt problem, I'd look into Gaussian Processes
instead of multi-scale MaxEnt, and then see what covariance functions were
needed for PhoSim starfields.

**Comment by rmjarvis** [comment]
I think this isn't going to happen.  Closing (without prejudice).
