### ISSUE TITLE
Will Piff select stars for you?

### ISSUE THREAD

**Issue by cpadavis** [rmjarvis/Piff#29]
I notice that even in the DES example it uses a catalog already processed by findstars. I bet we'll want Piff to one day select stars, too.

Where would this go? This seems like it should be an Input class, but I can also see it being some kind of Outlier class too, if your assessment of whether a star is _really_ a star is changing as you fit your PSF.

**Comment by RobertLuptonTheGood** [comment]
If you add an ability to select a catalogue, I'd make it as separate from piff as possible.  One of the first things I did in my python psfex bindings was to split out the built-in selector, and since then we've used at least two different ones (and will investigate moving to an external catalogue based on GAIA as soon as it's available)

**Comment by rmjarvis** [comment]
I was imagining having an option to select stars from the input catalog somewhere down the line.  Probably as a subfield of the `input` field in the config file.  (The selected stars would be included in the output file, but I think it makes more logical sense to consider this an aspect of the input processing.)

For starters, I would probably port over my findstars module, but it would be nice to easily have a few options to swap among.  And the default should probably remain to just use all the objects in the input file, so if you have an external truth catalog (like Gaia), then that would be easy.

But I don't think this is terribly high priority just now, since we have usable code to make star catalogs that seem to be working ok most of the time.
