### ISSUE TITLE
fit_des.py is broken and extraneous and probably should be deleted

### ISSUE THREAD

**Issue by cpadavis** [rmjarvis/Piff#37]
Here's a fun thing I learned:

just running nosetests in the tests directory currently doesn't run the test in fit_des. It looks like you need to have the file name have a test out front, and also have the function name be test_blah(); either change by itself won't work.

If you specifically run fit_des, you quickly find that the code is outdated and broken.

But then I looked more into it, and I think test_pixel does everything in fit_des anyways; fit_des.py has just been sitting in the tests directory silently broken for probably the past couple months.

So, is there any reason I shouldn't just delete fit_des.py?

**Comment by rmjarvis** [comment]
We could probably just get rid of fit_des.py at this point.  It was Gary's original code for testing the PixelGrid code.  I modified and adapted it to make the test_des_image function in test_pixel.py.  For a while that function called out to fit_des, but eventually all the functionality was migrated over, and the fit_des code was orphaned.

Since then, it has apparently become out of date and broken.  I don't think there is any reason to keep it anymore.

By the way, you are correct that nosetests will only run functions that start with `test`.  And without a filename argument, nosetests will run tests in all files that have `test` or `Test` anywhere in the filename.  This allows the test functions to use ancillary helper functions that aren't intended to be run directly.

**Comment by cpadavis** [comment]
Good to know! I've removed fit_des.py
