### ISSUE TITLE
Plotify

### ISSUE THREAD

**Issue by jmeyers314** [rmjarvis/Piff#56]
It would be nice to be able to take an existing piff yaml + output file, modify the plots section of the yaml file, and then remake the plots but without rerunning the actual fit.  I suggest "plotify" to be a script that reads a normal looking piff yaml file, but reads the .piff file in instead of writing it out, and then also remakes the plots.

**Comment by cpadavis** [comment]
one thing that you'll need to also add is the ability for stars to save their images / weight maps, and for plotify to handle both cases. I think the stats modules right now assume the stars have images / weights. Maybe we can get around that by saving the measured shapes and model shapes when we save the stars, since I think all of the stats modules right now work entirely in that space

**Comment by rmjarvis** [comment]
The idea is that it would read in the input files again according to the input field in the config file.  But then rather than running the solver to make the psf, it would read in file that is listed in the output field.  I don't think we want to be writing out all the images into the .piff file just for this kind of thing.

**Comment by rmjarvis** [comment]
Done.  PR #59.  Thanks Chris!
