### ISSUE TITLE
Jobs Being Deleted Without Email Message

### ISSUE THREAD

**Issue by areshernandez** [rmjarvis/Piff#61]
I wrote a program to run notest_optatmo.py several times with different numbers of stars as jobs. However, something went wrong with one set of jobs that I sent, which caused them to continue to run without stopping for awhile. To try to find out what was going on, I rewrote my program and ran it again with changes. However, it looks like any new jobs I send to the farm are being deleted soon after they are sent. I'm noticing that the "EXEC_HOST" is now always "fell_some_number" instead of "hequ_some_number."

The jobs that mysteriously dissappear don't appear in my email. I also manually ran the notest_optatmo.py and sent it as a job but the job also disappeared without a message in my email. Is there a large backlog of jobs currently preventing new ones from being finished?

**Comment by cpadavis** [comment]
This is a SLAC issue, not a piff issue -- it might be best to take this to
email or to the slack channel.

fell and hequ are different computer clusters, so that isn't a problem.
When you "bjobs" do you see these jobs there? Finally, are you using the
"-o" flag (which writes out to file)? If so, then you won't get an email.
